stages:
- base
- build
- test

image: docker:dind

base:
  stage: base
  script:
  - docker build -t harbor.listenrobot.com/ops/centos:zabbix ./base/
  - docker login --username=ops -p KYn16v9b  harbor.listenrobot.com
  - docker push harbor.listenrobot.com/ops/centos:zabbix
  - docker rmi harbor.listenrobot.com/ops/centos:zabbix
  only:
    - /base/

build:
  stage: build
  script:
  - docker build -t harbor.listenrobot.com/ops/zabbix:$CI_COMMIT_REF_NAME .
  - docker login --username=ops -p KYn16v9b  harbor.listenrobot.com
  - docker push harbor.listenrobot.com/ops/zabbix:$CI_COMMIT_REF_NAME
  only:
    - tags

test_sucess:
  stage: test
  script:
  - docker run --rm harbor.listenrobot.com/ops/zabbix:$CI_COMMIT_REF_NAME python /usr/lib/zabbix/alertscripts/dingrobot.py "build zabbix-deploy success {}".format($CI_COMMIT_REF_NAME)
  - docker rmi harbor.listenrobot.com/ops/zabbix:$CI_COMMIT_REF_NAME
  only:
    - tags

test_fails:
  stage: test
  script:
  - docker run --rm harbor.listenrobot.com/ops/zabbix:1.0.2 python /usr/lib/zabbix/alertscripts/dingrobot.py "build zabbix-deploy Fails {}".format($CI_COMMIT_REF_NAME)
  - docker rmi harbor.listenrobot.com/ops/zabbix:1.0.2
  when: on_failure
